# version: '3'

services:
  postgres:
    image: take0a/postgres-lgov
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - robonet
    ports:
      - 5432:5432
    restart: no
    environment:
      POSTGRES_PASSWORD: password

  mashu:
    image: roboninc/mashu:latest
    networks:
      - robonet
    ports:
      - 80:80
      - 3000:3000
    restart: no

volumes:
  postgres:

networks:
  robonet:
